### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by netosantosbr** [netosantosbr/GCMS-Jose-Alfredo#1]
[Readme](https://github.com/netosantosbr/GCMS-Jose-Alfredo/blob/main/README.md)

**Comment by ramidedantas** [comment]
José Alfreado, organize o Readme como está no meu repositório. Me marque aqui quando fizer.

**Comment by netosantosbr** [comment]
@ramidedantas Feito! :)

**Comment by ramidedantas** [comment]
@netosantosbr alteração realizada, pode fechar issue.

**Comment by netosantosbr** [comment]
@ramidedantas Certo. Obrigado!
